version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15.6
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run:
          name: "Print the Go version"
          command: go version
      - run:
          name: "Fetch dependencies"
          command: go mod download
      - run:
          name: "Run golint"
          command: >
            go get -u golang.org/x/lint/golint
            golint ./...
      - run:
          name: "Run go test (+ race detector)"
          command: go test -v -race ./...