name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Fetch Dependencies
      run: go mod download

    - name: Build
      run: go build -v ./...

    - name: Test + race detector
      run: go test -v -race ./...
